name: Metrics
on:
  # update per jam
  schedule: [{cron: "0 * * * *"}]
  # workflow update tiap jam
  workflow_dispatch:
  push: {branches: ["main", "master"]}
jobs:
  bellshadebot-fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: modifikasi last update dari file
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
      - name: commit perubahan
        run: |
          git config --global user.email "bellshade07@gmail.com"
          git config --global user.name "bellshadebot"
          git add -A
          timestamp=$(date '+%F %H:%M:%S %Z')
          git commit -m "Update Data ${timestamp}"
      - name: github push
        uses: ad-m/github-push-action@v0.5.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
